name: Update GitHub Profile Stats

on:
  schedule:
    - cron: "0 3 * * *"

  workflow_dispatch:

  push:
    paths:
      - ".github/workflows/profile-stats.yml"

permissions:
  contents: write

jobs:

  summary-cards:
    name: Generate GitHub Summary Cards
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate GitHub Profile Summary Cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        with:
          USERNAME: ${{ github.repository_owner }}
          BRANCH_NAME: "main"


  streak-stats:
    name: Generate Contribution Streak
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Streak Stats
        uses: DenverCoder1/github-readme-streak-stats@v1
        with:
          options: user=${{ github.repository_owner }}&theme=tokyonight&hide_border=true&disable_animations=true&timezone=Asia/Kolkata
          path: profile/streak.svg

      - name: Commit Streak Stats
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add profile/streak.svg

          git diff --cached --quiet || git commit -m "Update GitHub profile stats"

          git push
